language: go

go:
  - master

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  # - npm --prefix ./server install ./server

scripts:
  - cd client && go build
